# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 223ebbf31753e8ed5b9e88d6b9962770dfe64aeb07d354b859075a707c47af9f52841e4f51faa4eba537c9a3752942d8ec23e2b2c19e0e80a29fabb8fa0a53c3

test:
  secret_key_base: 52c620694f8ff31213a3d31b32eea59bff99c836722df7fcb4371ab4f7ed592ee5eb33aef97c001ba5a2ad2591f315df4da91ec8ea19cb0aefcf96ca58ac2ccb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
